---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(dplyr)
library(wordcloud2)
library(tidytext)
library(tidyverse)
library(plotly)

df <- read.csv("mental-heath-in-tech_working_copy.csv")
```

```{r }


# Plot a `worldcloud` of the most common health issues reported by the interviewees.
main_conditions <- df %>%
  #filter(Age > 40) %>%
  #filter(MHI_currently == "Yes") %>%
  select(Condition) %>%
  count(Condition) %>%
  setNames(c("word", "freq")) %>%
  anti_join(get_stopwords()) %>%
  arrange(desc(freq))

#View(main_conditions)

(main_conditions %>%
    wordcloud2(size = 1, minRotation = -pi/2, maxRotation = -pi/2, shape = "circle"))
```



```{r , echo=FALSE}
(df %>%
    ggplot(aes(x = scared_of_discussing_with_employer)) +
    geom_bar(stat = "count", position = position_dodge()) +
    geom_text(stat = "count", aes(label = ..count..), vjust = -0.4, colour = "black") +
    #ylim(0, 315) +
    labs(x = "XXX",
         y = "YYY") +
    theme_bw() +
    #ggtitle("Team_mem_view_negetively") +
    theme(plot.title = element_text(hjust = 0.5)))
```
```{r , echo=FALSE}
(df %>%
    ggplot(aes(x = options_for_seeking_help)) +
    geom_bar(stat = "count", position = position_dodge()) +
    geom_text(stat = "count", aes(label = ..count..), vjust = -0.4, colour = "blue") +
    #ylim(0, 315) +
    labs(x = "XXX",
         y = "YYY") +
    theme_bw() +
    #ggtitle("Team_mem_view_negetively") +
    theme(plot.title = element_text(hjust = 0.5)))
```
```{r}
#sought_treatment_by_professional
#MHI_in_past
#MHI_currently

df %>%
  ggplot(aes(x = options_for_seeking_help,fill =MHI_currently )) +
  geom_bar(stat = "count", position = position_dodge()) +
  facet_grid(~ MHI_in_past)
  
  

```
```{r}
df %>%
  ggplot(aes(x = options_for_seeking_help)) +
  geom_bar(aes(MHI_currently),stat = "count", position = position_dodge()) 
  #geom_bar(aes(MHI_in_past),stat = "count", position = position_dodge())

```

```{r}
df %>% filter(MHI_in_past == 'No')%>%
  ggplot(aes(x = options_for_seeking_help, fill =MHI_currently) ) + 
  geom_bar(position="dodge")
  #geom_bar(aes(MHI_currently),stat = "count", position = position_dodge()) 
  #geom_bar(aes(MHI_in_past),stat = "count", position = position_dodge())

```

```{r}

#wrk_interference_when_treated
#wrk_interference_No_treatement
df %>% filter(MHI_in_past == 'Yes')%>%
  ggplot(aes(x = wrk_interference_No_treatement, fill =MHI_currently) ) + 
  geom_bar(position="dodge")
```


```{r}
p1 <- plot_ly(df, x = ~wrk_interference_when_treated) %>% add_histogram()

p2 <- df %>%
  dplyr::count(wrk_interference_No_treatement) %>%
  plot_ly(x = ~wrk_interference_No_treatement, y = ~n) %>% 
  add_bars()

subplot(p1, p2) %>% hide_legend()
```

```{r}
(df_1 <- read.csv("mental-heath-in-tech_working_copy.csv"))

# Plot a `worldcloud` of the most common health issues reported by the interviewees.
main_conditions <- df_1 %>% 
  select(Condition) %>% 
  mutate(Condition = as.character(Condition)) %>% 
  mutate(Condition = tolower(Condition)) %>%
  mutate(Condition = gsub("\\s*\\([^\\)]+\\)", "", Condition)) %>%
  mutate(Condition = gsub("\\s+-.*", "", Condition)) %>%
  mutate(Condition = strsplit(Condition, "|", fixed = TRUE)) %>%
  unnest(Condition) %>%
  count(Condition) %>% 
  setNames(c("word", "freq")) %>%
  mutate(freq = log(freq)) %>% 
  arrange(desc(freq))


#View(main_conditions)

(main_conditions %>% 
    wordcloud2(size = 0.5, minRotation = 0, maxRotation = 0, shape = "circle"))
```

```{r}
plot1_filtered  <-df %>%      
                              filter(Age > input$age[1],  # lower limit in slidebar
                                     Age < input$age[2])
```